[package]
name = "snake"
version = "0.1.0"
authors = ["tensor-programming <abeltensor@tensor-programming.com>"]
edition = "2021"  # Include this to use modern Rust features

[dependencies]
rand = "0.8"  # Updated version
piston_window = "0.132"  # Updated version
